package action.user;

import java.io.IOException;
import java.util.concurrent.Callable;

public class test
{
    final String f="111";
    static boolean aBoolean;
    public static void main(String[] args) throws IOException
    {

    }
}

interface aa
{

}

class Base
{
    static int c=11;
    protected int d=12;
    private Base()
    {

    }
}

class test2
{


    public void t(int a,boolean d)
    {
        System.out.println(d);
    }
    public void t(boolean a,int d)
    {
        System.out.println(d);
    }

    public void tt(String s)
    {
        String st=new String();
        s="测试";
    }

    public static void main(String[] args)
    {
        int a;
        int b;

    }

}

class test3 implements Callable
{

    /**
     * Computes a result, or throws an exception if unable to do so.
     *
     * @return computed result
     * @throws Exception if unable to compute a result
     */
    public Object call() throws Exception
    {
        return null;
    }
}
